name: Deploy Release
on:
  push:
    branches: ['main']
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - '.typos.toml'

jobs:
  deploy:
    name: Deploy Release
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v5
      - name: Validate data
        run: ./gradlew validateData --stacktrace --console=colored
      - name: Deploy release version
        run: ./gradlew publishExportPublicationToPaperRepository --stacktrace --console=colored
        env:
          ORG_GRADLE_PROJECT_paperUsername: ${{ secrets.ARTIFACTORY_USERNAME }}
          ORG_GRADLE_PROJECT_paperPassword: ${{ secrets.ARTIFACTORY_PASSWORD }}
