on:
  - pull_request

name: Validate PR

jobs:
  build:
    name: Build and validate PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Validate data
        run: ./gradlew validateData

      - name: Upload ZIPs
        uses: actions/upload-artifact@v4
        with:
          name: export-zips
          path: build/exportZips/
